<<<<<<< HEAD
=======
name: Blockchain CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Build credit-score contract
      run: |
        cd contracts/credit-score
        cargo build --release
    
    - name: Test credit-score contract
      run: |
        cd contracts/credit-score
        cargo test

    - name: Build fraud-detect contract
      run: |
        cd contracts/fraud-detect
        cargo build --release
    
    - name: Test fraud-detect contract
      run: |
        cd contracts/fraud-detect
        cargo test

    - name: Build governance contract
      run: |
        cd contracts/governance
        cargo build --release
    
    - name: Test governance contract
      run: |
        cd contracts/governance
        cargo test

    - name: Upload contract artifacts
      uses: actions/upload-artifact@v4
      with:
        name: blockchain-contracts
        path: |
          contracts/**/target/release/*.rlib
          contracts/**/target/wasm32-unknown-unknown/release/*.wasm

>>>>>>> 3950e5c (workflow)
